OPENAI_API_KEY="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"
ASSISTANT_ID="asst_cQuf9u2IOCqrVkRrsL91ecnh"