OPENAI_API_KEY="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"
ASSISTANT_ID="asst_cQuf9u2IOCqrVkRrsL91ecnh"